# Generated by Django 5.0 on 2025-11-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="places/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("temple", "Temple"),
                            ("ghat", "Ghat"),
                            ("eatery", "Eatery"),
                            ("heritage", "Heritage Site"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="gallery/")),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="places.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.TextField(blank=True, null=True)),
                ("user_guides", models.TextField(blank=True, null=True)),
                ("did_you_know", models.TextField(blank=True, null=True)),
                (
                    "place",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="places.place",
                    ),
                ),
            ],
        ),
    ]
