# Generated by Django 5.0 on 2025-11-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
